In [1]:
from rlrom.trainers import RLTrainer
from rlrom.testers import RLTester
import os, sys, glob
from rlrom.utils import *
from pprint import pprint
import polars as pl
from datetime import date
import ipywidgets as widgets
from IPython.display import display
wd = os.getcwd()
print(wd) 

I0000 00:00:1791550502.315985  304328 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1791550502.346464  304328 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI AVX_VNNI_INT8 AVX_NE_CONVERT FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1791550503.107395  304328 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


/local/home/donzeal/workspace/rlrom/examples


In [2]:
w = widgets.Dropdown(
    options=[
        'cartpole/cfg0tr_ppo_go_right.yml',
        'cartpole/cfg0tr_ppo_go_left.yml',
        'cartpole/cfg0tr_ppo_specs.yml',
        'cartpole/cfg0tr_ppo.yml',
        'highway_env/cfg0tr.yml'])
display(w)


Dropdown(options=('cartpole/cfg0tr_ppo_go_right.yml', 'cartpole/cfg0tr_ppo_go_left.yml', 'cartpole/cfg0tr_ppo_…

In [3]:
os.chdir(wd)
cfg_file = w.value
print(cfg_file)
cfg = load_cfg(cfg_file)
T = RLTester(cfg)
print('-------------------------------------------------------------------------------------------')
training_folders = get_training_folders(cfg, verbose=1)

cartpole/cfg0tr_ppo_go_right.yml
loading field [ specs ] from STL file [ cartpole.stl ]
loading field [ ppo ] from YAML file [ cartpole_ppo.yml ]
-------------------------------------------------------------------------------------------
Scanning models in  /local/home/donzeal/workspace/rlrom/examples/cartpole/models
ppo_specs_go_right_2026_10_09__training1: 505.62327688049953
ppo_specs_go_right_2026_10_09__training4: 562.7036609903589
ppo_specs_go_right_2026_10_09__training2: 528.8084320495924
ppo_specs_go_right_2026_10_09__training3: 546.6708498615815
ppo_specs_go_right_2026_10_06__training1: 1795.5944080974964
ppo_specs_go_right_2026_10_06__training0: 1726.804310457225
ppo_specs_go_right_2026_10_09__training0: 13017.492565265955
ppo_specs_go_right_2026_10_06__training2: 1785.9800280478316


In [4]:
#print(isinstance(cfg,dict))
all_res = get_training_res(training_folders, 'all')

In [5]:
cfg_file, mdl_file, _ = get_best_models(all_res, 'all')

In [6]:
set_active_model(cfg, cfg_file, mdl_file)

ppo_specs_go_right_2026_10_06__training0/model_step_420000.zip


In [7]:
# Testing "Best" model
#m = get_step_model(cfg,100000)
show_active_model(cfg)
res = T.run_cfg_test()
pprint(res['res_all_ep'])

ppo_specs_go_right_2026_10_06__training0/model_step_420000.zip
INFO: Loading model  /local/home/donzeal/workspace/rlrom/examples/cartpole/models/ppo_specs_go_right.zip


/local/home/donzeal/workspace/rlrom/.venv/lib/python3.12/site-packages/stable_baselines3/common/on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(


loading PPO model succeeded
.
{'basics': {'mean_ep_len': np.float64(238.0),
            'mean_ep_rew': np.float64(1095.7106782793999)},
 'eval_formulas': {'cart_on_left': {'mean_mean': np.float64(-0.5540983685006646),
                                    'mean_num_sat': np.float64(21.0),
                                    'mean_sum': np.float64(-131.8754117031582)},
                   'phi_left_goal': {'mean_init_rob': np.float64(-0.23802801966667175),
                                     'ratio_init_sat': np.float64(0.0)}},
 'reward_formulas': {'go_right': {'mean_num_sat': np.float64(107.0),
                                  'mean_rob': np.float64(3.6038263793252097),
                                  'mean_sum': np.float64(857.7106782793999)}}}


In [13]:
T.run_episode(seed=6)

INFO: Loading model  /local/home/donzeal/workspace/rlrom/examples/cartpole/models/ppo_specs_go_right.zip
loading PPO model succeeded


{'observations': [array([ 0.0038, -0.0157, -0.0131, -0.0126], dtype=float32),
  array([ 0.0035,  0.1796, -0.0133, -0.3093], dtype=float32),
  array([ 0.0071, -0.0153, -0.0195, -0.0209], dtype=float32),
  array([ 0.0068,  0.1801, -0.0199, -0.3197], dtype=float32),
  array([ 0.0104,  0.3755, -0.0263, -0.6186], dtype=float32),
  array([ 0.0179,  0.1808, -0.0387, -0.3343], dtype=float32),
  array([ 0.0215, -0.0138, -0.0454, -0.0541], dtype=float32),
  array([ 0.0212,  0.1819, -0.0465, -0.3607], dtype=float32),
  array([ 0.0249, -0.0125, -0.0537, -0.0831], dtype=float32),
  array([ 0.0246,  0.1834, -0.0554, -0.3922], dtype=float32),
  array([ 0.0283, -0.0109, -0.0632, -0.1175], dtype=float32),
  array([ 0.0281, -0.2051, -0.0656,  0.1546], dtype=float32),
  array([ 0.024 , -0.0091, -0.0625, -0.158 ], dtype=float32),
  array([ 0.0238, -0.2033, -0.0656,  0.1144], dtype=float32),
  array([ 0.0197, -0.0073, -0.0633, -0.1983], dtype=float32),
  array([ 0.0196, -0.2014, -0.0673,  0.0738], dtype=fl

In [ ]:
get_df_mean_min_max_val(out_all,'mean_ep_rew')

In [ ]:
out_all.sort_values(by='mean_ep_rew',ascending=False)[['steps', 'training_idx', 'mean_ep_rew']]


In [ ]:
# plot training results
import rlrom.plots as rlp

df_all_training_files = get_df_all_training_files(cfg)

df = get_df_training(cfg, train_idx)
rlp.plot_df_training(df)



In [21]:
pprint(all_res[['steps', 'mean_ep_rew']])
#pprint(res['res']['cart_on_left'])


     steps  mean_ep_rew
0    10000   118.654566
1    20000   108.866424
2    30000   187.683283
3    40000   143.495552
4    50000   600.746264
5    60000   753.602209
6    70000   877.784578
7    80000  1343.484525
8    90000  1404.031625
9   100000  1126.496237
10  110000   623.593872
11  120000   670.868103
12  130000   823.023791
13  140000   535.036947
14  150000   887.481642
15  160000  1085.275240
16  170000   912.966395
17  180000   996.763476
18  190000   911.045613
19  200000  1038.773917
20  210000  1009.500293
21  220000  1068.365148
22  230000  1005.724345
23  240000  1058.756029
24  250000  1196.683225
25  260000   998.667606
26  270000   951.259889
27  280000   896.609178
28  290000  1004.032463
29  300000   784.305428
30  310000   707.420771
31  320000   731.146109
32  330000   979.499888
33  340000  1047.006117
34  350000  1246.416960
35  360000  1169.842068
36  370000  1019.906585
37  380000  1373.594030
38  390000  1017.593219
39  400000  1141.879032
40  410000  1238

In [ ]:
T.run_episode(seed=4)
d = T.env.get_wrapper_attr('stl_driver')
x = d.get_signal('x')
print(x)
ax = d.plot_signal('x')
d.plot_rob('cart_on_left', 0,90, ax=ax)


In [ ]:
print(d)